import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { AlertCircle, CheckCircle2, Eye, Plus, Trash2, Sparkles, PencilLine } from 'lucide-react';
import { useApp } from '@/contexts/AppContext';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';

interface MSBFindingsSectionProps {
  registrationId: string;
  registrationType: 'fintrac' | 'revenu_quebec';
}

const SEVERITY_CONFIG: Record<string, { label: string; variant: 'destructive' | 'default' | 'secondary' | 'outline' }> = {
  'complete_non_compliance': { label: 'Complete Non-Compliance', variant: 'destructive' },
  'partial_important': { label: 'Partial — Important', variant: 'destructive' },
  'partial_moderate': { label: 'Partial — Moderate', variant: 'default' },
  'partial_lesser': { label: 'Partial — Lesser', variant: 'secondary' },
  'observation': { label: 'Observation', variant: 'outline' },
};

const isAutoGenerated = (submodule: string | null) =>
  !!submodule && (submodule.startsWith('checklist:') || submodule.startsWith('change-notification:'));

export function MSBFindingsSection({ registrationId, registrationType }: MSBFindingsSectionProps) {
  const { selectedEngagement } = useApp();
  const queryClient = useQueryClient();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [manualForm, setManualForm] = useState({
    title: '',
    severity: 'observation',
    description: '',
    observation: '',
    regulation_reference: '',
    recommendation: '',
  });

  const { data: findings, isLoading } = useQuery({
    queryKey: ['msb-findings', selectedEngagement?.id],
    queryFn: async () => {
      if (!selectedEngagement?.id) return [];
      const { data, error } = await supabase
        .from('findings')
        .select('*')
        .eq('engagement_id', selectedEngagement.id)
        .eq('module', 'msb_registration')
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data || [];
    },
    enabled: !!selectedEngagement?.id,
  });

  const addManualMutation = useMutation({
    mutationFn: async (form: typeof manualForm) => {
      if (!selectedEngagement?.id) throw new Error('No engagement selected');
      if (!form.title.trim()) throw new Error('Title is required');
      const { error } = await supabase.from('findings').insert({
        engagement_id: selectedEngagement.id,
        module: 'msb_registration',
        submodule: `manual:${registrationType}:${registrationId}`,
        title: form.title.trim(),
        severity: form.severity,
        status: 'open',
        description: form.description || null,
        observation: form.observation || null,
        regulation_reference: form.regulation_reference || null,
        recommendation: form.recommendation || null,
        date_identified: new Date().toISOString().split('T')[0],
      });
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['msb-findings', selectedEngagement?.id] });
      toast.success('Manual entry added to Findings');
      setDialogOpen(false);
      setManualForm({ title: '', severity: 'observation', description: '', observation: '', regulation_reference: '', recommendation: '' });
    },
    onError: (e: any) => toast.error(e.message || 'Failed to add'),
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from('findings').delete().eq('id', id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['msb-findings', selectedEngagement?.id] });
      toast.success('Removed');
    },
    onError: (e: any) => toast.error(e.message || 'Failed to delete'),
  });

  const getSeverityConfig = (severity: string) =>
    SEVERITY_CONFIG[severity] || { label: severity, variant: 'outline' as const };

  const findingsCount = findings?.filter(f => f.severity !== 'observation').length || 0;
  const observationsCount = findings?.filter(f => f.severity === 'observation').length || 0;
  const autoCount = findings?.filter(f => isAutoGenerated(f.submodule)).length || 0;
  const manualCount = (findings?.length || 0) - autoCount;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-32">
        <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Summary */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-start justify-between gap-3 flex-wrap">
            <div>
              <CardTitle>Findings, Recommendations & Observations</CardTitle>
              <CardDescription>
                Auto-pulled from the Audit Checklist (Fail items) and Change Detection (30-day gaps). Add manual observations below.
              </CardDescription>
            </div>
            <div className="flex gap-2 flex-wrap">
              <Badge variant="outline" className="gap-1"><Sparkles className="h-3 w-3" />{autoCount} Auto</Badge>
              <Badge variant="outline" className="gap-1"><PencilLine className="h-3 w-3" />{manualCount} Manual</Badge>
              {findingsCount > 0 && <Badge variant="destructive">{findingsCount} Finding{findingsCount !== 1 ? 's' : ''}</Badge>}
              {observationsCount > 0 && <Badge variant="secondary">{observationsCount} Observation{observationsCount !== 1 ? 's' : ''}</Badge>}
              {findingsCount === 0 && observationsCount === 0 && <Badge variant="default">No Issues</Badge>}
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DialogTrigger asChild>
              <Button variant="default" size="sm">
                <Plus className="h-4 w-4 mr-2" />
                Add Manual Finding / Observation
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-2xl">
              <DialogHeader>
                <DialogTitle>Add Manual Finding or Observation</DialogTitle>
                <DialogDescription>
                  Capture any issue noticed that was not automatically flagged by the checklist or change detection.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="m-title">Title *</Label>
                  <Input
                    id="m-title"
                    value={manualForm.title}
                    onChange={(e) => setManualForm({ ...manualForm, title: e.target.value })}
                    placeholder="Short summary of the issue"
                  />
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label>Severity</Label>
                    <Select value={manualForm.severity} onValueChange={(v) => setManualForm({ ...manualForm, severity: v })}>
                      <SelectTrigger><SelectValue /></SelectTrigger>
                      <SelectContent>
                        <SelectItem value="complete_non_compliance">Complete Non-Compliance</SelectItem>
                        <SelectItem value="partial_important">Partial — Important</SelectItem>
                        <SelectItem value="partial_moderate">Partial — Moderate</SelectItem>
                        <SelectItem value="partial_lesser">Partial — Lesser</SelectItem>
                        <SelectItem value="observation">Observation</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="m-ref">Regulation Reference</Label>
                    <Input
                      id="m-ref"
                      value={manualForm.regulation_reference}
                      onChange={(e) => setManualForm({ ...manualForm, regulation_reference: e.target.value })}
                      placeholder="e.g., PCMLTFR s.11.13"
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="m-desc">Description</Label>
                  <Textarea id="m-desc" rows={2}
                    value={manualForm.description}
                    onChange={(e) => setManualForm({ ...manualForm, description: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="m-obs">Observation</Label>
                  <Textarea id="m-obs" rows={2}
                    value={manualForm.observation}
                    onChange={(e) => setManualForm({ ...manualForm, observation: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="m-rec">Recommendation</Label>
                  <Textarea id="m-rec" rows={2}
                    value={manualForm.recommendation}
                    onChange={(e) => setManualForm({ ...manualForm, recommendation: e.target.value })}
                  />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button>
                <Button onClick={() => addManualMutation.mutate(manualForm)} disabled={addManualMutation.isPending}>
                  {addManualMutation.isPending ? 'Saving...' : 'Add Entry'}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </CardContent>
      </Card>

      {/* Findings */}
      {(!findings || findings.length === 0) ? (
        <Card>
          <CardContent className="py-12 text-center">
            <CheckCircle2 className="h-10 w-10 text-primary mx-auto mb-3" />
            <p className="font-medium">No findings or observations recorded</p>
            <p className="text-sm text-muted-foreground mt-1">
              Findings from the audit checklist and change detection will appear here automatically. You can also add manual entries.
            </p>
          </CardContent>
        </Card>
      ) : (
        findings.map((finding) => {
          const config = getSeverityConfig(finding.severity);
          const auto = isAutoGenerated(finding.submodule);
          return (
            <Card key={finding.id} className={finding.severity !== 'observation' ? 'border-destructive/20' : ''}>
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3">
                    {finding.severity === 'observation' ? (
                      <Eye className="h-5 w-5 text-muted-foreground mt-0.5 shrink-0" />
                    ) : (
                      <AlertCircle className="h-5 w-5 text-destructive mt-0.5 shrink-0" />
                    )}
                    <div>
                      <CardTitle className="text-base">{finding.title}</CardTitle>
                      <div className="flex items-center gap-2 mt-1">
                        {auto ? (
                          <Badge variant="outline" className="gap-1 text-[10px]"><Sparkles className="h-2.5 w-2.5" />Auto-generated</Badge>
                        ) : (
                          <Badge variant="outline" className="gap-1 text-[10px]"><PencilLine className="h-2.5 w-2.5" />Manual</Badge>
                        )}
                        {finding.submodule && (
                          <p className="text-xs text-muted-foreground">{finding.submodule}</p>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="flex gap-2 shrink-0 items-center">
                    <Badge variant={config.variant}>{config.label}</Badge>
                    <Badge variant="outline" className="text-xs">{finding.status}</Badge>
                    {!auto && (
                      <Button
                        variant="ghost" size="icon"
                        onClick={() => deleteMutation.mutate(finding.id)}
                        title="Delete manual entry"
                      >
                        <Trash2 className="h-4 w-4 text-destructive" />
                      </Button>
                    )}
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                {finding.description && (
                  <div className="space-y-1">
                    <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Description</p>
                    <p className="text-sm">{finding.description}</p>
                  </div>
                )}
                {finding.observation && (
                  <div className="space-y-1">
                    <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Observation</p>
                    <p className="text-sm">{finding.observation}</p>
                  </div>
                )}
                {finding.regulation_reference && (
                  <div className="space-y-1">
                    <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Regulatory Reference</p>
                    <p className="text-sm">{finding.regulation_reference}</p>
                  </div>
                )}
                {finding.recommendation && (
                  <div className="space-y-1 p-3 bg-muted/50 rounded-lg">
                    <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Recommendation</p>
                    <p className="text-sm">{finding.recommendation}</p>
                  </div>
                )}
                {finding.management_response && (
                  <div className="space-y-1 p-3 border rounded-lg">
                    <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Management Response</p>
                    <p className="text-sm">{finding.management_response}</p>
                    {finding.management_response_owner && (
                      <p className="text-xs text-muted-foreground">Owner: {finding.management_response_owner}</p>
                    )}
                    {finding.target_remediation_date && (
                      <p className="text-xs text-muted-foreground">Target Date: {finding.target_remediation_date}</p>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          );
        })
      )}
    </div>
  );
}
