
INSERT INTO public.risk_assessment_question_templates
  (section_code, section_name, control_area, control_objective, test_procedure, expected_outcome, sort_order) VALUES
('CUS', 'Customer Risk', 'Client Segmentation Approach', 'Does the Company assess clients individually or via logical groupings (segments)?', 'Review client risk-rating methodology for individual vs. segment-based approach', 'Approach (individual or segment) is documented and consistently applied', 162),
('CUS', 'Customer Risk', 'Documented Client Risk Factors', 'Are client risk factors documented (profile, occupation, business type, expected activity)?', 'Review client risk profiles for documented risk factors', 'Risk factors are captured for each client or segment', 164),
('CUS', 'Customer Risk', 'Products & Delivery Channels in Relationship', 'Does relationship-based assessment consider products and delivery channels used by the client?', 'Review whether RBA links client risk to products/channels they use', 'Client risk reflects products and delivery channels in use', 166),
('CUS', 'Customer Risk', 'Client Geography & Transaction Flow', 'Does it consider client geography and transaction destination or source?', 'Review whether client risk incorporates geography of client and counterparties', 'Geography and transaction source/destination feed client risk rating', 168),
('CUS', 'Customer Risk', 'Client Characteristics & Patterns', 'Does it consider client characteristics and transactional patterns?', 'Review whether transactional behavior is factored into client risk', 'Client characteristics and patterns are reflected in risk rating', 172),
('CUS', 'Customer Risk', 'Higher-Risk Indicators Reflected', 'Are higher-risk indicators reflected (third parties, complexity, unknown source of funds)?', 'Review treatment of third parties, complexity, and unknown SOF in client risk', 'Higher-risk indicators elevate client risk where present', 174),
('CUS', 'Customer Risk', 'Mandatory High-Risk Triggers', 'Are mandatory high-risk triggers treated as high risk (listed person property, foreign PEP, unconfirmed BO with SMO)?', 'Review classification of mandatory high-risk triggers per FINTRAC', 'Listed persons, foreign PEPs, and unconfirmed BO + SMO are always rated high risk', 176);
