-- Add columns to question templates to support the full working paper structure
ALTER TABLE public.aml_program_question_templates
  ADD COLUMN IF NOT EXISTS regulatory_category text,
  ADD COLUMN IF NOT EXISTS test_procedure text,
  ADD COLUMN IF NOT EXISTS analyst_guidance text,
  ADD COLUMN IF NOT EXISTS pass_criteria text,
  ADD COLUMN IF NOT EXISTS max_points integer DEFAULT 2,
  ADD COLUMN IF NOT EXISTS section_code text,
  ADD COLUMN IF NOT EXISTS section_name text,
  ADD COLUMN IF NOT EXISTS question_code text,
  ADD COLUMN IF NOT EXISTS is_new_or_updated boolean DEFAULT false;

-- Add columns to control results to support working paper output
ALTER TABLE public.aml_pp_control_results
  ADD COLUMN IF NOT EXISTS risk_rating text,
  ADD COLUMN IF NOT EXISTS points_achieved integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS observation_best_practice text,
  ADD COLUMN IF NOT EXISTS evidence_reviewed text;

-- Clear existing core_controls templates (we are replacing with full working paper)
DELETE FROM public.aml_program_question_templates
WHERE submodule = 'policies_procedures' AND control_area = 'core_controls';

-- Insert the full working paper as core_controls questions
-- Section 0: Document Control & Governance
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','document_control_governance',1,'Policy title and scope','PCMLTFA',true,1,'Requirement','Confirm the policy/manual has a formal title and scope statement','Look for the document title, business scope, legal entity scope, and effective date.','Document has a formal title, identifies the reporting entity or group, and clearly states the scope of activities covered.',2,'0','Document Control & Governance','DCG-01',false),
('policies_procedures','core_controls','document_control_governance',2,'Version control','PCMLTFR',false,2,'Best Practice','Review version history and change tracking','Look for version number, revision date, author/reviewer, and summary of changes.','Policy includes version number, revision history, date of issue/update, and identifiable owner.',2,'0','Document Control & Governance','DCG-02',false),
('policies_procedures','core_controls','document_control_governance',3,'Approval and dating','PCMLTFR',true,3,'Requirement','Confirm policy is approved and dated','Look for senior management or board approval evidence and effective date.','Policy is approved by the appropriate governance body, dated, and current.',2,'0','Document Control & Governance','DCG-03',false),
('policies_procedures','core_controls','document_control_governance',4,'Regulatory references','PCMLTFA',true,4,'Requirement','Confirm the policy references the Canadian AML/ATF framework','Look for references to PCMLTFA, PCMLTFR, FINTRAC guidance, sanctions laws, Ministerial Directives, and related legal instruments.','Policy references the PCMLTFA, its regulations, applicable FINTRAC guidance, and sanctions / related legislation relevant to the business.',2,'0','Document Control & Governance','DCG-04',false),
('policies_procedures','core_controls','document_control_governance',5,'Alignment to operations','PCMLTFR',false,5,'Requirement','Assess whether the policy reflects actual products, services, channels, and jurisdictions','Compare policy language to the business model and products offered.','Policy is tailored to the entity''s business model and is not generic or inconsistent with operations.',2,'0','Document Control & Governance','DCG-05',false);

-- Section 1: Effective Compliance Regime
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','effective_compliance_regime',6,'Compliance program pillars','PCMLTFR 71',true,6,'Requirement','Confirm the AML/ATF program includes all required elements','The five elements are: compliance officer, written policies and procedures, risk assessment, training program, and effectiveness review.','All required pillars of the compliance regime are explicitly documented.',2,'1','Effective Compliance Regime','ECR-01',false),
('policies_procedures','core_controls','effective_compliance_regime',7,'Compliance officer appointment','PCMLTFR 71',true,7,'Requirement','Confirm a compliance officer / CAMLO is appointed','Look for designation language, authority, and reporting line.','A qualified compliance officer is formally designated with responsibility for the program.',2,'1','Effective Compliance Regime','ECR-02',false),
('policies_procedures','core_controls','effective_compliance_regime',8,'Policies and procedures pillar','PCMLTFR 71',false,8,'Requirement','Confirm written policies and procedures are identified as a required element',NULL,'Written policies/procedures are expressly included and linked to operations.',2,'1','Effective Compliance Regime','ECR-03',false),
('policies_procedures','core_controls','effective_compliance_regime',9,'Risk assessment','PCMLTFR 71',true,9,'Requirement','Confirm a documented risk assessment exists','Look for risks across clients, products, services, delivery channels, geography and other relevant factors.','The policy requires a documented and periodically updated risk assessment.',2,'1','Effective Compliance Regime','ECR-04',false),
('policies_procedures','core_controls','effective_compliance_regime',10,'Training program','PCMLTFR 71',true,10,'Requirement','Confirm the policy includes a training program element','Look for who is trained, frequency, content, delivery method, records, and updates.','Training is documented as a core component of the compliance regime.',2,'1','Effective Compliance Regime','ECR-05',false),
('policies_procedures','core_controls','effective_compliance_regime',11,'Effectiveness review','PCMLTFR 71',true,11,'Requirement','Confirm an effectiveness review is required','Look for independent review frequency and remediation tracking.','Policy requires an effectiveness review at least every two years and tracking of remediation.',2,'1','Effective Compliance Regime','ECR-06',false);

-- Section 2: Roles & Responsibilities
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','roles_responsibilities',12,'Board / directors oversight','PCMLTFR',true,12,'Requirement','Review responsibilities of the board or directors','Look for approval, oversight, challenge, resourcing, and review of material issues.','Directors or the governing body have clearly assigned oversight responsibilities for AML/ATF compliance.',2,'2','Roles & Responsibilities','RR-01',false),
('policies_procedures','core_controls','roles_responsibilities',13,'Owners / controlling mind responsibilities','PCMLTFR',false,13,'Requirement','Confirm owners'' responsibilities are addressed where applicable','Applicable especially for smaller entities or owner-managed MSBs.','Policy allocates accountability to owners or principals for supporting and resourcing compliance.',2,'2','Roles & Responsibilities','RR-02',false),
('policies_procedures','core_controls','roles_responsibilities',14,'Senior management responsibilities','PCMLTFR',true,14,'Requirement','Review responsibilities of senior management','Look for operational ownership, escalation handling, approval of high-risk matters, and support for compliance.','Senior management duties are defined, including escalation, support, and timely remediation.',2,'2','Roles & Responsibilities','RR-03',false),
('policies_procedures','core_controls','roles_responsibilities',15,'Compliance officer responsibilities','PCMLTFR',true,15,'Requirement','Assess the detail of the compliance officer''s role','Look for regulatory liaison, reporting, policy maintenance, monitoring, training, and escalation.','The compliance officer''s duties, authority, independence, and access to information are clearly documented.',2,'2','Roles & Responsibilities','RR-04',false),
('policies_procedures','core_controls','roles_responsibilities',16,'Employee responsibilities','PCMLTFR',true,16,'Requirement','Review employee and front-line obligations','Look for KYC, escalation, reporting, sanctions screening, confidentiality, and training participation.','Employees'' AML/ATF responsibilities are clearly defined.',2,'2','Roles & Responsibilities','RR-05',false),
('policies_procedures','core_controls','roles_responsibilities',17,'Segregation and escalation','FINTRAC Guidance',false,17,'Best Practice','Confirm that the appointed compliance officer of a larger corporation is not directly involved in the receipt, transfer or payment of funds.','Look for independence in review/approval and formal escalation routes.','As a best practice, the appointed compliance officer of a larger business should not be directly involved in the receipt, transfer or payment of funds.',2,'2','Roles & Responsibilities','RR-06',false);

-- Section 3: MSB Registration & FINTRAC Filings
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','msb_registration_filings',18,'Registration before commencing business','PCMLTFR',true,18,'Requirement','Confirm policy states MSB registration must occur before operations begin','This is a hard timing requirement for MSBs / FMSBs.','Policy explicitly states the business must be registered with FINTRAC before beginning MSB activities.',2,'3','MSB Registration & FINTRAC Filings','MSB-01',false),
('policies_procedures','core_controls','msb_registration_filings',19,'Renewal before expiry / every two years','PCMLTFR',true,19,'Requirement','Confirm renewal timing is documented','Look for explicit requirement to renew before expiry and at least every two years, as applicable.','Policy states registration must be renewed before expiry and within the required two-year cycle.',2,'3','MSB Registration & FINTRAC Filings','MSB-02',false),
('policies_procedures','core_controls','msb_registration_filings',20,'Update of FINTRAC registration information within 30 days','PCMLTFR',true,20,'Requirement','Confirm update obligations are documented','Look for updates to ownership, compliance officer, address, services, business name, or other registration information.','Policy requires FINTRAC registration information to be updated within 30 days of a relevant change.',2,'3','MSB Registration & FINTRAC Filings','MSB-03',false),
('policies_procedures','core_controls','msb_registration_filings',21,'Cessation notification within 30 days','PCMLTFR',true,21,'Requirement','Confirm cessation procedures are documented','Look for process when the business ceases MSB activities.','Policy requires FINTRAC to be notified within 30 days after the business ceases MSB activities.',2,'3','MSB Registration & FINTRAC Filings','MSB-04',false),
('policies_procedures','core_controls','msb_registration_filings',22,'Supporting registration records','PCMLTFR',true,22,'Requirement','Confirm the policy requires retention of MSB registration evidence','Look for registrations, renewals, change notices, correspondence, and proof of submission.','Policy requires retention of MSB registration, renewal, update, and cessation records.',2,'3','MSB Registration & FINTRAC Filings','MSB-05',false),
('policies_procedures','core_controls','msb_registration_filings',23,'Inquiry from FINTRAC','PCMLTFR',true,23,'Requirement','Confirm the policy requires response to FINTRAC within 30 days of such inquiry.','Look for statement that says that FINTRAC''s inquiry must be responded to within 30 days of such inquiry.','Policy clearly states FINTRAC''s inquiry must be responded to within 30 days of such inquiry.',2,'3','MSB Registration & FINTRAC Filings','MSB-06',false);

-- Section 4: Legal & Regulatory Framework
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','legal_regulatory_framework',24,'PCMLTFA and regulations referenced','PCMLTFA / PCMLTFR',true,24,'Requirement','Confirm the policy references the Act and regulations','Look for full name or accepted short forms: PCMLTFA and PCMLTFR.','Policy references the governing Act and regulations applicable to the reporting entity.',2,'4','Legal & Regulatory Framework','LRF-01',false),
('policies_procedures','core_controls','legal_regulatory_framework',25,'FINTRAC guidance referenced','FINTRAC Guidance',false,25,'Best Practice','Confirm relevant FINTRAC guidance is referenced or incorporated','Look for client identification, beneficial ownership, reporting, sanctions-evasion, and 24-hour rule guidance.','Policy references or embeds relevant FINTRAC guidance supporting operational compliance.',2,'4','Legal & Regulatory Framework','LRF-02',false),
('policies_procedures','core_controls','legal_regulatory_framework',26,'Sanctions legislation referenced','UN Act / SEMA / JVCFOA',true,26,'Requirement','Confirm sanctions framework is addressed','Look for United Nations Act, Special Economic Measures Act, Justice for Victims of Corrupt Foreign Officials Act and related sanctions obligations, as relevant.','Relevant sanctions legislation and screening obligations are referenced.',2,'4','Legal & Regulatory Framework','LRF-03',false),
('policies_procedures','core_controls','legal_regulatory_framework',27,'Ministerial Directives - Russia and DPRK / North Korea','Ministerial Directives',true,27,'Requirement','Confirm Ministerial Directives are captured','Look for current requirements relevant to Russia and the DPRK/North Korea, including heightened controls and transaction restrictions where applicable.','Policy captures the Ministerial Directive obligations applicable to Russia and the DPRK/North Korea and operational steps for compliance.',2,'4','Legal & Regulatory Framework','LRF-04',false),
('policies_procedures','core_controls','legal_regulatory_framework',28,'Ministerial Directive - Islamic Republic of Iran','Ministerial Directive (Nov 2025)',true,28,'Requirement','Confirm the updated Iran directive is captured','Look for the November 2025 update and procedures for enhanced controls, reporting and restrictions where applicable to the reporting entity.','Policy captures the updated Ministerial Directive obligations applicable to Iran and operational steps for compliance.',2,'4','Legal & Regulatory Framework','LRF-05',true),
('policies_procedures','core_controls','legal_regulatory_framework',29,'Correspondent banking and foreign relationships','PCMLTFR',false,29,'Requirement','If applicable, confirm correspondent banking / foreign affiliate requirements are addressed','Look for due diligence, approvals, and restrictions linked to higher-risk jurisdictions and directives.','Policy includes correspondent banking / foreign affiliate controls where relevant to the business.',2,'4','Legal & Regulatory Framework','LRF-06',false);

-- Section 5: Client Identification & Verification
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','client_identification_verification',30,'Identity verification triggers','PCMLTFR',true,30,'Requirement','Confirm the policy lists all events that trigger identification / verification','Look for account opening, large cash, large VC, EFT, remittance or funds transfer of $1,000 or more, VC transfer of $1,000 or more, FX of $3,000 or more, suspicious transactions, prepaid products, trust-related triggers, and other sector-specific triggers.','Policy explicitly lists all applicable trigger events for verifying persons and entities.',2,'5','Client Identification & Verification','KYC-01',true),
('policies_procedures','core_controls','client_identification_verification',31,'Keeping identification information current','PCMLTFR',true,31,'Requirement','Confirm the policy addresses updating client identification information','Look for refresh frequency based on risk and material change triggers.','Policy requires client identification information to be kept current based on risk and business relationship activity.',2,'5','Client Identification & Verification','KYC-02',false),
('policies_procedures','core_controls','client_identification_verification',32,'Exemptions documented','PCMLTFR',false,32,'Requirement','Assess whether identification exemptions are addressed where applicable','Look for documented exceptions such as certain deposits to business accounts, public bodies, and permitted exemptions.','Applicable exemptions are documented and not applied broadly or inaccurately.',2,'5','Client Identification & Verification','KYC-03',false),
('policies_procedures','core_controls','client_identification_verification',33,'Government-issued photo identification method','PCMLTFR',true,33,'Requirement','Review the photo ID method criteria','Look for authentic, valid, current ID; acceptable forms; in-person vs non-face-to-face requirements; and recordkeeping.','Policy sets out acceptable photo ID requirements, authenticity/validity/currentness tests, and method-specific recordkeeping.',2,'5','Client Identification & Verification','KYC-04',false),
('policies_procedures','core_controls','client_identification_verification',34,'Credit file method criteria','PCMLTFR',true,34,'Requirement','Review the credit file method criteria','Look for the credit file existing for at least 3 years, containing at least 2 trade lines, and matching name, date of birth, and address; plus steps when there is a mismatch.','Policy states the credit file criteria and requires contemporaneous use, independent sourcing, mismatch handling, and recordkeeping.',2,'5','Client Identification & Verification','KYC-05',false),
('policies_procedures','core_controls','client_identification_verification',35,'Dual-process method criteria','PCMLTFR',true,35,'Requirement','Review the dual-process method','Look for two independent and reliable sources confirming name + address, or name + DOB, or name + account relationship.','Policy describes the dual-process method, independence/reliability of sources, and recordkeeping requirements.',2,'5','Client Identification & Verification','KYC-06',false),
('policies_procedures','core_controls','client_identification_verification',36,'Affiliate / member method','PCMLTFR',false,36,'Requirement','If used, review the affiliate / member method requirements','Look for conditions, required matching information, and prior acceptable verification by the affiliate/member.','Policy sets out when the affiliate / member method can be used and required controls.',2,'5','Client Identification & Verification','KYC-07',false),
('policies_procedures','core_controls','client_identification_verification',37,'Reliance method','PCMLTFR',false,37,'Requirement','If used, confirm reliance on another reporting entity / affiliated foreign entity is addressed','Look for conditions of reliance, governance, and records to obtain and retain.','Policy defines reliance conditions, controls, and recordkeeping.',2,'5','Client Identification & Verification','KYC-08',false),
('policies_procedures','core_controls','client_identification_verification',38,'Agent or mandatary verification','PCMLTFR',true,38,'Requirement','Confirm using an agent or mandatary is addressed','Look for written agreement, information transfer, and validation of method used by the agent/mandatary.','Policy requires written arrangements and sufficient information to satisfy the reporting entity about the verification performed.',2,'5','Client Identification & Verification','KYC-09',false),
('policies_procedures','core_controls','client_identification_verification',39,'Children and clients lacking standard identification','PCMLTFR',false,39,'Requirement','If applicable, confirm procedures for special cases','Look for procedures for children, parents/guardians, and clients without standard identification for eligible products.','Policy addresses special verification scenarios applicable to the business.',2,'5','Client Identification & Verification','KYC-10',false),
('policies_procedures','core_controls','client_identification_verification',40,'Entity verification method','PCMLTFR',true,40,'Requirement','Confirm the policy addresses verifying entities','Look for confirmation of existence, reliance, simplified identification where permitted, and required data for corporations, trusts, NPOs, etc.','Policy defines acceptable methods to verify entity existence and required information to retain.',2,'5','Client Identification & Verification','KYC-11',false),
('policies_procedures','core_controls','client_identification_verification',41,'Entity recordkeeping','PCMLTFR',true,41,'Requirement','Review entity-related recordkeeping requirements','Look for company name, address, directors, incorporation details, business nature, and supporting records.','Policy clearly states the records to retain for entity verification.',2,'5','Client Identification & Verification','KYC-12',false);

-- Section 6: Business Relationships & Ongoing Monitoring
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','business_relationships_monitoring',42,'When a business relationship is established','PCMLTFR',true,42,'Requirement','Confirm the policy defines when a business relationship begins','Rules differ by sector; look for account opening, second verification event within 5 years, service agreements, or first required verification in certain sectors.','Policy accurately defines when a business relationship is formed for the applicable sector.',2,'6','Business Relationships & Ongoing Monitoring','BR-01',false),
('policies_procedures','core_controls','business_relationships_monitoring',43,'Intended nature / purpose of relationship','PCMLTFR',true,43,'Requirement','Confirm the policy requires documenting purpose and intended nature','Look for account purpose, expected activity, products/services, and purpose of the relationship.','Policy requires documentation of the intended nature and purpose of the business relationship.',2,'6','Business Relationships & Ongoing Monitoring','BR-02',false),
('policies_procedures','core_controls','business_relationships_monitoring',44,'When a business relationship ends','PCMLTFR',false,44,'Requirement','Confirm the policy defines when a business relationship ends','Look for closure, inactivity rules, termination, and final offboarding triggers where relevant.','Policy defines end-of-relationship criteria or events relevant to the business.',2,'6','Business Relationships & Ongoing Monitoring','BR-03',false),
('policies_procedures','core_controls','business_relationships_monitoring',45,'Ongoing monitoring requirement','PCMLTFR',true,45,'Requirement','Confirm ongoing monitoring is required','Look for monitoring of transactions, KYC refresh, consistency with expected activity, and suspicious activity review.','Policy requires ongoing monitoring of business relationships based on risk.',2,'6','Business Relationships & Ongoing Monitoring','BR-04',false),
('policies_procedures','core_controls','business_relationships_monitoring',46,'Risk-based monitoring frequency','PCMLTFR',true,46,'Requirement','Confirm monitoring intensity varies by risk','Look for more frequent review for high-risk relationships and material change triggers.','Policy links risk ratings to the nature, frequency, and depth of monitoring.',2,'6','Business Relationships & Ongoing Monitoring','BR-05',false),
('policies_procedures','core_controls','business_relationships_monitoring',47,'Enhanced due diligence for high-risk clients and transactions','PCMLTFR',true,47,'Requirement','Confirm EDD procedures are documented','Look for high-risk triggers, additional source-of-funds/source-of-wealth review, enhanced monitoring, more frequent refresh, and senior approval where required.','Policy defines enhanced due diligence procedures for high-risk clients and high-risk transactions.',2,'6','Business Relationships & Ongoing Monitoring','BR-06',false),
('policies_procedures','core_controls','business_relationships_monitoring',48,'Derisking / demarketing procedures','FINTRAC Guidance',false,48,'Best Practice','Assess whether the policy addresses exiting or restricting relationships','Look for criteria, governance, approvals, fair treatment, recordkeeping, and linkage to risk or control failures.','Policy documents derisking/demarketing procedures and governance as a best-practice control.',2,'6','Business Relationships & Ongoing Monitoring','BR-07',false);

-- Section 7: Third Party Determination
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','third_party_determination',49,'Definition of third party','PCMLTFR',false,49,'Requirement','Confirm the policy defines who a third party is','Look for distinctions between the client/conductor and another person or entity instructing or benefiting from the transaction.','Policy includes a clear and accurate third-party definition.',2,'7','Third Party Determination','TPD-01',false),
('policies_procedures','core_controls','third_party_determination',50,'Triggers for third party determination','PCMLTFR',true,50,'Requirement','Confirm the policy states when third-party determination is required','Look for large cash transactions, large virtual currency transactions, account opening / signature cards, and when an information record is created, as applicable.','Policy identifies all applicable situations requiring third-party determination.',2,'7','Third Party Determination','TPD-02',false),
('policies_procedures','core_controls','third_party_determination',51,'How to make the determination','PCMLTFR',false,51,'Requirement','Confirm the policy explains how staff determine whether a third party is involved','Look for asking the client, review of documentation, and escalation if the answer is unclear.','Policy gives clear operational steps for making and documenting the determination.',2,'7','Third Party Determination','TPD-03',false),
('policies_procedures','core_controls','third_party_determination',52,'Third party recordkeeping','PCMLTFR',true,52,'Requirement','Review required information to be recorded','Look for name, address, telephone number if applicable, DOB, occupation/nature of business, relationship to client, and corporation-specific data where relevant.','Policy specifies the recordkeeping requirements when a third party is identified.',2,'7','Third Party Determination','TPD-04',false),
('policies_procedures','core_controls','third_party_determination',53,'Unable to determine / suspicion of third party involvement','PCMLTFR',false,53,'Requirement','Confirm escalation exists where a determination cannot be made','Look for documentation of uncertainty and escalation where third-party involvement is suspected.','Policy requires documentation and escalation where third-party involvement is suspected but cannot be confirmed.',2,'7','Third Party Determination','TPD-05',false);

-- Section 8: Beneficial Ownership & Discrepancy Reporting
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','beneficial_ownership_discrepancy',54,'Beneficial ownership identification threshold','PCMLTFR',true,54,'Requirement','Confirm the policy identifies the applicable threshold and ownership/control concepts','Look for individuals who directly or indirectly own or control 25% or more, plus structure/control information.','Policy requires identification of individuals who directly or indirectly own or control 25% or more, and documentation of ownership/control structure.',2,'8','Beneficial Ownership & Discrepancy Reporting','BO-01',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',55,'BO Cannot be another corporation','PCMLTFR',false,55,'Requirement','Confirm that the policy states that BO cannot be other corporations, trusts or other entities. They must be the individuals who are the owners or controllers of the entity.','Look out for a statement that says BO cannot be another corporation. It must be a natural person.','BO must be a natural person, not another entity.',2,'8','Beneficial Ownership & Discrepancy Reporting','BO-02',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',56,'Corporation, trust, and other entity requirements','PCMLTFR',true,56,'Requirement','Confirm the policy captures different entity types','Look for directors for corporations, trustees/beneficiaries/settlors for trusts, and equivalent information for other entities.','Policy accurately sets out beneficial ownership requirements by entity type.',2,'8','Beneficial Ownership & Discrepancy Reporting','BO-03',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',57,'How BO information is obtained and confirmed','PCMLTFR',true,57,'Requirement','Review procedures for obtaining and validating BO information','Look for source documents, registries, questionnaires/certifications, and independent corroboration where appropriate.','Policy describes how beneficial ownership information is obtained and reasonable measures are taken to confirm accuracy.',2,'8','Beneficial Ownership & Discrepancy Reporting','BO-04',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',58,'Unable to confirm beneficial ownership','PCMLTFR',true,58,'Requirement','Confirm escalation procedures when BO cannot be confirmed','Look for documenting measures taken, assigning high risk, enhanced due diligence, and senior escalation.','Policy requires documentation of efforts, escalation, high-risk treatment, and enhanced measures when BO cannot be confirmed.',2,'8','Beneficial Ownership & Discrepancy Reporting','BO-05',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',59,'No beneficial owner exists','PCMLTFR',false,59,'Requirement','Confirm procedures exist where no beneficial owner exists','Look for documenting why no beneficial owner exists and what measures/supporting information led to that conclusion.','Policy requires documentation of the rationale and evidence where no beneficial owner exists.',2,'8','Beneficial Ownership & Discrepancy Reporting','BO-06',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',60,'Beneficial ownership discrepancy reporting to Corporations Canada','Corporations Canada (Oct 1, 2025)',true,60,'Requirement','Confirm the policy captures discrepancy reporting','As of October 1, 2025, look for procedures where a material discrepancy is identified between BO information obtained and ISC information in Corporations Canada''s database, including timing and acknowledgement retention.','Policy requires material beneficial ownership discrepancies to be reported to Corporations Canada within the required timeline and requires retention of the acknowledgement/notice.',2,'8','Beneficial Ownership & Discrepancy Reporting','BO-07',true),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',61,'Escalation to FINTRAC where discrepancy is suspicious','PCMLTFR',true,61,'Requirement','Confirm linkage between BO discrepancies and suspicious transaction analysis','Look for internal escalation and STR consideration where a discrepancy gives rise to reasonable grounds to suspect ML/TF or sanctions-evasion-related concerns.','Policy requires BO discrepancies that indicate suspicious activity to be escalated and assessed for FINTRAC reporting.',2,'8','Beneficial Ownership & Discrepancy Reporting','BO-08',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',62,'Recordkeeping for BO measures and acknowledgements','PCMLTFR',true,62,'Requirement','Confirm recordkeeping requirements for discrepancy reporting','Look for records of searches, discrepancy analysis, reporting submissions, and acknowledgement notices.','Policy requires retention of BO due diligence and discrepancy reporting records.',2,'8','Beneficial Ownership & Discrepancy Reporting','BO-09',false);

-- Section 9: PEP / HIO / Family / Close Associate Controls
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','pep_hio_controls',63,'PEP/HIO definitions','PCMLTFR',false,63,'Requirement','Confirm the policy defines foreign PEPs, domestic PEPs, HIOs, family members, and close associates','Look for clear definitions and examples relevant to onboarding and ongoing monitoring.','Policy includes accurate definitions for PEPs, HIOs, family members, and close associates.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-01',false),
('policies_procedures','core_controls','pep_hio_controls',64,'When PEP/HIO determination must be made','PCMLTFR',true,64,'Requirement','Confirm timing of PEP/HIO determination','Look for onboarding, periodic review, when facts change, and for high-value EFT or VC transactions where applicable.','Policy states when PEP/HIO determinations must be performed.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-02',false),
('policies_procedures','core_controls','pep_hio_controls',65,'How PEP/HIO status is determined','PCMLTFR',false,65,'Requirement','Review methods for identifying PEP/HIO status','Look for asking the client, reliable databases, credible sources, and escalation of potential matches.','Policy sets out acceptable methods and escalation for PEP/HIO determination.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-03',false),
('policies_procedures','core_controls','pep_hio_controls',66,'Foreign PEP treatment','PCMLTFR',true,66,'Requirement','Confirm the policy treats foreign PEPs appropriately','Look for high-risk classification and required enhanced measures.','Policy requires foreign PEPs to be treated as high risk and subject to enhanced due diligence.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-04',false),
('policies_procedures','core_controls','pep_hio_controls',67,'Domestic PEP lifecycle','PCMLTFR',false,67,'Requirement','Confirm the policy states when domestic PEP status starts and ends','Look for the 5-year cessation rule after leaving office or death.','Policy states that a domestic PEP ceases to be a PEP 5 years after leaving office or becoming deceased.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-05',false),
('policies_procedures','core_controls','pep_hio_controls',68,'HIO lifecycle','PCMLTFR',false,68,'Requirement','Confirm the policy states when HIO status starts and ends','Look for the 5-year cessation rule after leaving office or death.','Policy states that an HIO ceases to be an HIO 5 years after leaving office or becoming deceased.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-06',false),
('policies_procedures','core_controls','pep_hio_controls',69,'Family member lifecycle','PCMLTFR',false,69,'Requirement','Confirm the policy addresses family-member timing','Look for status linked to the related domestic PEP/HIO lifecycle.','Policy explains when family members are captured and when that status ends.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-07',false),
('policies_procedures','core_controls','pep_hio_controls',70,'Close associate lifecycle','PCMLTFR',false,70,'Requirement','Confirm the policy explains when a close associate ceases to be one','Look for cessation when the close association no longer exists.','Policy states that close-associate status ends when the relevant relationship ceases.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-08',false),
('policies_procedures','core_controls','pep_hio_controls',71,'Source of funds, source of wealth, and senior management approval','PCMLTFR',true,71,'Requirement','Confirm required measures when PEP/HIO status is identified','Look for source of funds, source of wealth, senior management review/approval, and enhanced monitoring.','Policy requires source of funds, source of wealth, senior management approval, and enhanced monitoring where required.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-09',false),
('policies_procedures','core_controls','pep_hio_controls',72,'PEP/HIO recordkeeping','PCMLTFR',true,72,'Requirement','Confirm recordkeeping requirements are defined','Look for how the determination was made, dates, source-of-funds/wealth information, approvals, and monitoring records.','Policy specifies the recordkeeping requirements for PEP/HIO determinations and related actions.',2,'9','PEP / HIO / Family / Close Associate Controls','PEP-10',false);

-- Section 10: Reporting Requirements
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','reporting_requirements',73,'LCTR threshold and timing','PCMLTFR',true,73,'Requirement','Confirm the policy states the large cash reporting threshold and deadline','Look for $10,000 threshold and filing within 15 calendar days.','Policy states the LCTR threshold and filing deadline accurately.',2,'10','Reporting Requirements','REP-01',false),
('policies_procedures','core_controls','reporting_requirements',74,'LVCTR threshold and timing','PCMLTFR',true,74,'Requirement','Confirm the policy states the large virtual currency threshold and deadline','Look for $10,000 equivalent threshold and filing within 5 working days.','Policy states the LVCTR threshold and filing deadline accurately.',2,'10','Reporting Requirements','REP-02',false),
('policies_procedures','core_controls','reporting_requirements',75,'EFTR threshold and timing','PCMLTFR',true,75,'Requirement','Confirm the policy states EFTR triggers and timing','Look for reportable incoming/outgoing international EFTs of $10,000 or more and filing within 5 working days.','Policy states the EFTR trigger and filing deadline accurately.',2,'10','Reporting Requirements','REP-03',false),
('policies_procedures','core_controls','reporting_requirements',76,'Travel rule coverage','PCMLTFR',false,76,'Requirement','Confirm the policy addresses the travel rule where applicable','Look for travel-rule treatment for EFTR and LVCTR processes.','Policy addresses travel-rule requirements applicable to EFTR and LVCTR.',2,'10','Reporting Requirements','REP-04',false),
('policies_procedures','core_controls','reporting_requirements',77,'Static 24-hour aggregation window','PCMLTFR',true,77,'Requirement','Confirm the reporting entity has defined a static 24-hour period','Look for a fixed 24-hour window (not rolling) defined by the reporting entity, potentially by report type, and applied consistently.','Policy defines the entity''s static 24-hour aggregation period(s) and applies them consistently for applicable reports.',2,'10','Reporting Requirements','REP-05',false),
('policies_procedures','core_controls','reporting_requirements',78,'Aggregation by conductor, beneficiary, or third party','PCMLTFR',false,78,'Requirement','Confirm the policy explains aggregation logic','Look for aggregation by conductor, beneficiary, and/or third party as applicable to the report type.','Policy states the applicable aggregation logic, including conductor, beneficiary, and third-party considerations.',2,'10','Reporting Requirements','REP-06',false),
('policies_procedures','core_controls','reporting_requirements',79,'Foreign currency conversion for threshold determination','PCMLTFR',false,79,'Requirement','Confirm foreign currency threshold conversion is addressed','Look for use of the Bank of Canada exchange rate in effect at the time of the transaction to determine whether the $10,000 CAD threshold is met.','Policy requires foreign-currency transactions to be converted to CAD using the applicable Bank of Canada exchange rate when assessing thresholds.',2,'10','Reporting Requirements','REP-07',false),
('policies_procedures','core_controls','reporting_requirements',80,'Documentation of exchange-rate source','PCMLTFR',true,80,'Requirement','Confirm the source of exchange rate must be documented','Look for retention of the exchange-rate source and supporting evidence.','Policy requires documentation of the source of the exchange rate used and retention for audit trail purposes.',2,'10','Reporting Requirements','REP-08',false),
('policies_procedures','core_controls','reporting_requirements',81,'Definition of resident for reporting purposes','PCMLTFR',false,81,'Requirement','Confirm the policy defines resident for reporting purposes','Especially relevant to EFTR reporting and classification.','Policy includes a clear definition of resident for reporting purposes where applicable.',2,'10','Reporting Requirements','REP-09',false),
('policies_procedures','core_controls','reporting_requirements',82,'Suspicious transaction reporting - attempted and completed transactions','PCMLTFR',true,82,'Requirement','Confirm the policy includes attempted and completed STRs','Look for both attempted and completed transactions and clear escalation criteria.','Policy requires reporting of suspicious attempted and completed transactions where required.',2,'10','Reporting Requirements','REP-10',false),
('policies_procedures','core_controls','reporting_requirements',83,'STR internal timeline after investigation concludes','PCMLTFR',true,83,'Requirement','Confirm the policy defines an internal submission timeline','As soon as practicable still requires an internal SLA or timeline once the investigation is concluded.','Policy states that STRs must be filed as soon as practicable and defines an internal deadline after investigation conclusion.',2,'10','Reporting Requirements','REP-11',false),
('policies_procedures','core_controls','reporting_requirements',84,'STR recall and 20-day resubmission','PCMLTFR',false,84,'Requirement','Confirm the policy addresses recalled STRs','Look for a stated 20-day resubmission requirement when an STR is recalled.','Policy states that recalled STRs must be corrected and resubmitted within 20 days.',2,'10','Reporting Requirements','REP-12',false),
('policies_procedures','core_controls','reporting_requirements',85,'Red flags / examples of suspicious transactions','FINTRAC Guidance',true,85,'Requirement','Confirm the policy contains suspicious-activity indicators','Look for sector-relevant red flags and typologies to support staff judgment and escalation.','Policy includes relevant suspicious-activity red flags/examples and escalation guidance.',2,'10','Reporting Requirements','REP-13',false),
('policies_procedures','core_controls','reporting_requirements',86,'Sanctions-evasion reporting','PCMLTFR',true,86,'Requirement','Confirm the policy addresses sanctions-evasion-related suspicious transactions','Look for STR filing expectations where sanctions-evasion suspicion exists and combined-report logic where multiple offences are suspected.','Policy addresses sanctions-evasion-related suspicious transaction reporting requirements.',2,'10','Reporting Requirements','REP-14',false),
('policies_procedures','core_controls','reporting_requirements',87,'Listed person or entity property reporting','PCMLTFR',true,87,'Requirement','Confirm the policy addresses the listed person or entity property report','Look for the current report replacing the earlier property-report approach and procedures to file/report as applicable.','Policy addresses the listed person or entity property report and related internal escalation and filing steps.',2,'10','Reporting Requirements','REP-15',false),
('policies_procedures','core_controls','reporting_requirements',88,'Terrorist property handling and reporting','PCMLTFA',true,88,'Requirement','Confirm listed person or entity property obligations are addressed','Look for immediate handling, disclosure to RCMP/CSIS, FINTRAC reporting, and prohibition on completing certain transactions where required.','Policy addresses terrorist property escalation, disclosure, and reporting requirements.',2,'10','Reporting Requirements','REP-16',false),
('policies_procedures','core_controls','reporting_requirements',89,'Submission methods and quality control','FINTRAC Guidance',false,89,'Requirement','Confirm the policy tells staff how reports are filed (portal/API/manual fallback where relevant).','Look for FINTRAC Web Reporting, API/F2R, approvals, and correction/recall controls. Fallback/manual paths.','Policy documents approved submission channels and quality-control steps for regulatory reports.',2,'10','Reporting Requirements','REP-17',false);

-- Section 11: Law Enforcement, Disclosure & Non-Compliance
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','law_enforcement_disclosure',90,'Production orders','PCMLTFA',true,90,'Requirement','Confirm the policy addresses production orders','Look for legal review, chain of custody, confidentiality, response timelines, and recordkeeping.','Policy sets out how production orders are received, escalated, responded to, and recorded.',2,'11','Law Enforcement, Disclosure & Non-Compliance','LED-01',false),
('policies_procedures','core_controls','law_enforcement_disclosure',91,'Law enforcement requests','PCMLTFA',true,91,'Requirement','Confirm the policy addresses requests from law enforcement or competent authorities','Look for controlled intake, escalation, legal/compliance review, response approval, and confidentiality.','Policy defines how law-enforcement requests are handled and documented.',2,'11','Law Enforcement, Disclosure & Non-Compliance','LED-02',false),
('policies_procedures','core_controls','law_enforcement_disclosure',92,'FINTRAC disclosure or clarification requests','PCMLTFA',true,92,'Requirement','Confirm procedures exist for FINTRAC requests','Look for response ownership, timelines, evidence gathering, and approval.','Policy sets out how FINTRAC requests or clarifications are handled and documented.',2,'11','Law Enforcement, Disclosure & Non-Compliance','LED-03',false),
('policies_procedures','core_controls','law_enforcement_disclosure',93,'Voluntary self-declaration of non-compliance','FINTRAC Guidance',false,93,'Requirement','Confirm the policy addresses self-disclosure to FINTRAC','Look for internal escalation, decision-making criteria, approvals, communication with FINTRAC, and remediation tracking.','Policy defines when non-compliance must be escalated, when voluntary self-disclosure is considered, and how remediation is tracked.',2,'11','Law Enforcement, Disclosure & Non-Compliance','LED-04',false),
('policies_procedures','core_controls','law_enforcement_disclosure',94,'Confidentiality and tipping off restrictions','PCMLTFA',true,94,'Requirement','Confirm confidentiality expectations are documented','Look for limitations on disclosure and handling of sensitive AML reporting information.','Policy includes appropriate confidentiality and anti-tipping-off controls.',2,'11','Law Enforcement, Disclosure & Non-Compliance','LED-05',false);

-- Section 12: Recordkeeping
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','recordkeeping',95,'Recordkeeping framework','PCMLTFR',true,95,'Requirement','Confirm the policy contains a general recordkeeping section','Look for records to retain, retention period, storage, accessibility, and responsibility.','Policy defines required records, retention rules, and storage/access controls.',2,'12','Recordkeeping','RK-01',false),
('policies_procedures','core_controls','recordkeeping',96,'Retention period','PCMLTFR',true,96,'Requirement','Confirm the retention period is stated','Look for minimum 5-year retention where applicable.','Policy states the minimum required retention period and any sector-specific nuances.',2,'12','Recordkeeping','RK-02',false),
('policies_procedures','core_controls','recordkeeping',97,'Reports retained','PCMLTFR',true,97,'Requirement','Confirm copies of reports are retained','Look for STRs, LCTRs, LVCTRs, EFTRs, property-related reports, and related acknowledgements/corrections where applicable.','Policy requires retention of copies of reports submitted to FINTRAC and related reporting records.',2,'12','Recordkeeping','RK-03',false),
('policies_procedures','core_controls','recordkeeping',98,'Client and business relationship records','PCMLTFR',true,98,'Requirement','Confirm client/account/business-relationship records are covered','Look for account/application records, intended use, signature cards, operating agreements, statements, trust records, and equivalent sector-specific records.','Policy specifies the client and relationship records to be retained.',2,'12','Recordkeeping','RK-04',false),
('policies_procedures','core_controls','recordkeeping',99,'Transaction records','PCMLTFR',true,99,'Requirement','Confirm transaction recordkeeping is documented','Look for large cash records, $3,000 records, EFT/VC transfer records, FX tickets, VC exchange tickets, money order/traveller''s cheque records, etc., as applicable.','Policy specifies the transaction records to be created and retained.',2,'12','Recordkeeping','RK-05',false),
('policies_procedures','core_controls','recordkeeping',100,'Recordkeeping for third party, BO, PEP, and sanctions controls','PCMLTFR',true,100,'Requirement','Confirm special AML records are retained','Look for third-party determinations, BO measures, discrepancy reports, PEP/HIO records, screening matches, and approvals.','Policy requires retention of special AML control records and supporting evidence.',2,'12','Recordkeeping','RK-06',false),
('policies_procedures','core_controls','recordkeeping',101,'Agent oversight records','PCMLTFR',false,101,'Requirement','If agents are used, confirm records and agreements are retained','Look for agreements, due diligence, audits, and remediation records.','Policy requires retention of agent oversight documentation.',2,'12','Recordkeeping','RK-07',false);

-- Section 13: Training Program
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','training_program',102,'Training policy exists','PCMLTFR 71',true,102,'Requirement','Confirm a documented training policy/program exists','Look for a defined program, governance, and curriculum ownership.','Policy includes a documented AML/ATF training program.',2,'13','Training Program','TRN-01',false),
('policies_procedures','core_controls','training_program',103,'Who must be trained','PCMLTFR 71',true,103,'Requirement','Confirm the policy states who must be trained','Look for employees, management, compliance staff, relevant contractors/agents, and board or directors where appropriate.','Policy identifies all personnel and relevant third parties who must receive AML/ATF training.',2,'13','Training Program','TRN-02',false),
('policies_procedures','core_controls','training_program',104,'When training must occur','PCMLTFR 71',false,104,'Requirement','Confirm onboarding and ongoing training timing is documented','Look for training at hire/role start and periodic refresh training.','Policy requires training at onboarding and at a defined ongoing frequency.',2,'13','Training Program','TRN-03',false),
('policies_procedures','core_controls','training_program',105,'Training frequency','PCMLTFR 71',false,105,'Requirement','Confirm training frequency is documented','Look for at least annual refresh or a risk-based more frequent cadence.','Policy sets a clear minimum training frequency and refresh requirements.',2,'13','Training Program','TRN-04',false),
('policies_procedures','core_controls','training_program',106,'Training content','PCMLTFR 71',true,106,'Requirement','Confirm required content is described','Look for AML obligations, KYC/CDD, reporting, sanctions, suspicious indicators, internal escalation, confidentiality, and regulatory updates.','Policy describes core training content and requires updates for regulatory changes.',2,'13','Training Program','TRN-05',false),
('policies_procedures','core_controls','training_program',107,'Method of delivery','PCMLTFR 71',false,107,'Requirement','Confirm the program describes delivery methods','Look for in-person, virtual, LMS, attestations, and testing where relevant.','Policy specifies delivery method(s) and how completion/understanding is evidenced.',2,'13','Training Program','TRN-06',false),
('policies_procedures','core_controls','training_program',108,'Role-based / enhanced training','PCMLTFR 71',false,108,'Requirement','Confirm higher-risk or specialist roles receive enhanced training','Look for additional training for compliance, operations, investigators, or high-risk product teams.','Policy requires role-based or enhanced training for relevant staff.',2,'13','Training Program','TRN-07',false),
('policies_procedures','core_controls','training_program',109,'Training recordkeeping','PCMLTFR 71',true,109,'Requirement','Confirm training records are retained','Look for attendance, completion dates, content/version, scores/attestations, and follow-up.','Policy requires retention of training completion and evidence records.',2,'13','Training Program','TRN-08',false);

-- Section 14: Agents, Correspondents & Special Relationships
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','agents_correspondents',110,'Use of agents / mandataries','PCMLTFR',true,110,'Requirement','Confirm agent/mandatary arrangements are governed','Look for written agreements, responsibilities, due diligence, and audit/oversight rights.','Policy governs the use of agents/mandataries and retains accountability with the reporting entity.',2,'14','Agents, Correspondents & Special Relationships','ACS-01',false),
('policies_procedures','core_controls','agents_correspondents',111,'Agent due diligence and audit','PCMLTFR',true,111,'Requirement','Confirm due diligence and ongoing oversight of agents','Look for validation, periodic review, audits, remediation, and termination rights.','Policy requires due diligence and ongoing monitoring of agents.',2,'14','Agents, Correspondents & Special Relationships','ACS-02',false),
('policies_procedures','core_controls','agents_correspondents',112,'Correspondent banking relationship controls','PCMLTFR',false,112,'Requirement','If applicable, confirm correspondent banking relationship requirements are documented','Look for due diligence before entering the relationship, senior approval, ongoing monitoring, and recordkeeping.','Policy documents controls for correspondent banking relationships where applicable.',2,'14','Agents, Correspondents & Special Relationships','ACS-03',false);