-- Policies & Procedures module — full working-paper rebuild
--
-- Replaces the legacy 120-question library with the firm's Excel working
-- paper (~100 controls across 14 sections) and switches scoring from a
-- uniform 2-point system to the FINTRAC harm-done taxonomy.
--
-- What this migration does:
-- 1. Adds `subsection` to `aml_program_question_templates`
--    (new Section → Subsection → Question hierarchy).
-- 2. Adds `finding_type` to `aml_pp_control_results` so each row can carry
--    a FINTRAC classification picked by the analyst.
-- 3. Adds `overall_finding_type` to `aml_pp_reviews` for the single overall
--    P&P verdict (keeps legacy `overall_design_rating` for backwards compat).
-- 4. Soft-deletes the existing core_controls templates for
--    `policies_procedures` (preserves any captured responses).
-- 5. Inserts the new control set using the firm's control IDs
--    (DCG-, ECR-, RR-, MSB-, KYC-, BR-, TPD-, BO-, PEP-, REP-, SAN-, RK-,
--    TRN-, LED-) with `analyst_guidance` = the analyst test and
--    `pass_criteria` = the pass criterion from the spreadsheet.
-- 6. Drops the obsolete dedicated "Agents, Correspondents & Special
--    Relationships" section — agent oversight survives via RK-07.

-- =========================================================================
-- 1. Schema additions
-- =========================================================================

ALTER TABLE public.aml_program_question_templates
  ADD COLUMN IF NOT EXISTS subsection text;

ALTER TABLE public.aml_pp_control_results
  ADD COLUMN IF NOT EXISTS finding_type text;

ALTER TABLE public.aml_pp_reviews
  ADD COLUMN IF NOT EXISTS overall_finding_type text,
  ADD COLUMN IF NOT EXISTS overall_finding_type_overridden boolean NOT NULL DEFAULT false;

-- =========================================================================
-- 2. Soft-delete legacy P&P core_controls templates
-- =========================================================================

UPDATE public.aml_program_question_templates
SET is_active = false
WHERE submodule = 'policies_procedures'
  AND control_area = 'core_controls';

-- =========================================================================
-- 3. Insert the firm's working paper
-- =========================================================================
-- Each row carries:
--   section_code  — numeric section label ('1' .. '14')
--   section_name  — full section title
--   subsection    — subsection name from the spreadsheet
--   question_code — firm's control ID (DCG-01, etc.)
--   question_text — "Control Area" column from the spreadsheet
--   analyst_guidance — "Analyst test / what to check" column
--   pass_criteria    — "Pass criteria" column
--   evidence_required = true for every row (P&P review always needs the doc)
--   max_points = NULL (we no longer score; finding_type is per-response)
--   regulatory_reference — best-fit primary reference per section

-- ---------------- Section 1: Document Control & Governance ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','document_control_governance',1,'Policy title','PCMLTFR',true,1,'Requirement',NULL,'Confirm the policy/procedure manual has a formal title and clearly identifies the document owner.','Document title and owner are clearly shown.',NULL,'1','Document Control & Governance','Document Control','DCG-01',false),
('policies_procedures','core_controls','document_control_governance',2,'Version control','PCMLTFR',true,2,'Requirement',NULL,'Confirm the document carries version number, issue date, effective date and next/review date.','Versioning and dates are visible and internally consistent.',NULL,'1','Document Control & Governance','Document Control','DCG-02',false),
('policies_procedures','core_controls','document_control_governance',3,'Approval evidence','PCMLTFR',true,3,'Requirement',NULL,'Confirm the policy is approved by the appropriate authority (Board / directors / senior management) and dated.','Approval authority, approver name/role and date are documented.',NULL,'1','Document Control & Governance','Approval','DCG-03',false),
('policies_procedures','core_controls','document_control_governance',4,'Amendment history','PCMLTFR',true,4,'Requirement',NULL,'Confirm a change log or revision history exists and reflects recent amendments.','Change history identifies what changed, when, and by whom.',NULL,'1','Document Control & Governance','Change log','DCG-04',false),
('policies_procedures','core_controls','document_control_governance',5,'Core AML/ATF laws','PCMLTFA / PCMLTFR',true,5,'Requirement',NULL,'Confirm the policy references the PCMLTFA and its Regulations, and aligns internal obligations to those legal instruments.','PCMLTFA and PCMLTFR are expressly cited and used as governing references.',NULL,'1','Document Control & Governance','Legislative references','DCG-05',false),
('policies_procedures','core_controls','document_control_governance',6,'Sanctions / related laws','UN Act / SEMA / JVCFOA / Criminal Code',true,6,'Requirement',NULL,'Confirm the policy references sanctions-related legislation relevant to the business (e.g., SEMA, United Nations Act, Justice for Victims of Corrupt Foreign Officials Act, Criminal Code / RIUNRST where relevant).','Relevant sanctions / terrorist property statutes are referenced or cross-referenced.',NULL,'1','Document Control & Governance','Legislative references','DCG-06',false),
('policies_procedures','core_controls','document_control_governance',7,'FINTRAC guidance','FINTRAC Guidance',true,7,'Requirement',NULL,'Confirm the policy references FINTRAC guidance and internal procedures where operational interpretation is required.','Policy cross-references current FINTRAC guidance and/or internal playbooks.',NULL,'1','Document Control & Governance','Guidance references','DCG-07',false);

-- ---------------- Section 2: Effective Compliance Regime ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','effective_compliance_regime',8,'Complete compliance regime','PCMLTFR s.71',true,8,'Requirement',NULL,'Confirm the policy states that the firm maintains an effective compliance regime/program.','Policy expressly refers to an effective compliance regime/program.',NULL,'2','Effective Compliance Regime','Five pillars','ECR-01',false),
('policies_procedures','core_controls','effective_compliance_regime',9,'Compliance officer pillar','PCMLTFR s.71',true,9,'Requirement',NULL,'Confirm the compliance officer pillar is addressed.','The role is expressly included as a required program element.',NULL,'2','Effective Compliance Regime','Five pillars','ECR-02',false),
('policies_procedures','core_controls','effective_compliance_regime',10,'Policies and procedures pillar','PCMLTFR s.71',true,10,'Requirement',NULL,'Confirm written policies and procedures are identified as a required element.','Written policies/procedures are expressly included and linked to operations.',NULL,'2','Effective Compliance Regime','Five pillars','ECR-03',false),
('policies_procedures','core_controls','effective_compliance_regime',11,'Risk assessment pillar','PCMLTFR s.71',true,11,'Requirement',NULL,'Confirm a documented risk assessment is identified as a required element.','Risk assessment is expressly included and tied to controls/monitoring.',NULL,'2','Effective Compliance Regime','Five pillars','ECR-04',false),
('policies_procedures','core_controls','effective_compliance_regime',12,'Training pillar','PCMLTFR s.71',true,12,'Requirement',NULL,'Confirm training is identified as a required element.','Training program is expressly included and described at a high level.',NULL,'2','Effective Compliance Regime','Five pillars','ECR-05',false),
('policies_procedures','core_controls','effective_compliance_regime',13,'Effectiveness review pillar','PCMLTFR s.71',true,13,'Requirement',NULL,'Confirm effectiveness review/testing is identified as a required element.','Effectiveness review is expressly included with a defined cadence.',NULL,'2','Effective Compliance Regime','Five pillars','ECR-06',false);

-- ---------------- Section 3: Roles & Responsibilities ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','roles_responsibilities',14,'Directors / Board oversight','PCMLTFR',true,14,'Requirement',NULL,'Confirm directors / Board (or equivalent) responsibilities are defined.','Oversight, approval, challenge and remediation oversight responsibilities are documented.',NULL,'3','Roles & Responsibilities','Governance','RR-01',false),
('policies_procedures','core_controls','roles_responsibilities',15,'Owners','PCMLTFR',true,15,'Requirement',NULL,'Confirm owners'' responsibilities are defined where applicable.','Owners'' accountability for providing truthful ownership information and supporting compliance is documented.',NULL,'3','Roles & Responsibilities','Governance','RR-02',false),
('policies_procedures','core_controls','roles_responsibilities',16,'Senior management','PCMLTFR',true,16,'Requirement',NULL,'Confirm senior management responsibilities are defined.','Senior management is responsible for resourcing, supporting and acting on escalation/reporting.',NULL,'3','Roles & Responsibilities','Management','RR-03',false),
('policies_procedures','core_controls','roles_responsibilities',17,'Compliance officer','PCMLTFR s.71',true,17,'Requirement',NULL,'Confirm the compliance officer role, authority, independence and reporting line are defined.','Role includes authority, independence, access to records/resources and escalation rights.',NULL,'3','Roles & Responsibilities','Compliance','RR-04',false),
('policies_procedures','core_controls','roles_responsibilities',18,'Segregation of Duties','FINTRAC Guidance',true,18,'Best Practice',NULL,'Confirm that the appointed compliance officer of a larger corporation is not directly involved in the receipt, transfer or payment of funds.','As a best practice, the appointed compliance officer of a larger business should not be directly involved in the receipt, transfer or payment of funds.',NULL,'3','Roles & Responsibilities','Compliance','RR-05',false),
('policies_procedures','core_controls','roles_responsibilities',19,'Employees / front line','PCMLTFR',true,19,'Requirement',NULL,'Confirm employee responsibilities are defined.','Employees must follow procedures, complete training, identify/escalate unusual activity and maintain confidentiality.',NULL,'3','Roles & Responsibilities','Operations','RR-06',false),
('policies_procedures','core_controls','roles_responsibilities',20,'Internal reporting','PCMLTFR',true,20,'Requirement',NULL,'Confirm escalation pathways are defined.','Operational staff know when and to whom to escalate KYC, BO, PEP, reporting and sanctions issues.',NULL,'3','Roles & Responsibilities','Escalation','RR-07',false);

-- ---------------- Section 4: MSB Registration & FINTRAC Notifications ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','msb_registration_filings',21,'Initial registration timing','PCMLTFR',true,21,'Requirement',NULL,'Confirm the policy states MSB/FMSB registration must occur before business commences.','Policy clearly says no MSB activity may start before registration is in place.',NULL,'4','MSB Registration & FINTRAC Notifications','Registration','MSB-01',false),
('policies_procedures','core_controls','msb_registration_filings',22,'Renewal timing','PCMLTFR',true,22,'Requirement',NULL,'Confirm the policy states renewal must occur before expiry and recognizes the 2-year registration validity period.','Renewal timing and validity period are clearly stated.',NULL,'4','MSB Registration & FINTRAC Notifications','Registration','MSB-02',false),
('policies_procedures','core_controls','msb_registration_filings',23,'30-day update rule','PCMLTFR s.11.13',true,23,'Requirement',NULL,'Confirm the policy requires updates to FINTRAC within 30 days of a change.','30-day update rule is stated for ownership, address, activities/services and other material changes.',NULL,'4','MSB Registration & FINTRAC Notifications','Registration','MSB-03',false),
('policies_procedures','core_controls','msb_registration_filings',24,'Cessation notice','PCMLTFR',true,24,'Requirement',NULL,'Confirm the policy requires cessation/termination notice within 30 days after the business ceases.','Policy clearly states FINTRAC must be notified within 30 days of cessation.',NULL,'4','MSB Registration & FINTRAC Notifications','Registration','MSB-04',false),
('policies_procedures','core_controls','msb_registration_filings',25,'Recordkeeping for registration lifecycle','PCMLTFR',true,25,'Requirement',NULL,'Confirm procedures retain evidence of registration, renewals, updates and cessation filings.','Acknowledgements/submissions are retained and accessible.',NULL,'4','MSB Registration & FINTRAC Notifications','Registration','MSB-05',false),
('policies_procedures','core_controls','msb_registration_filings',26,'Inquiry from FINTRAC','PCMLTFR',true,26,'Requirement',NULL,'Confirm the policy requires response to FINTRAC within 30 days of such inquiry.','Policy clearly states FINTRAC''s inquiry must be responded to within 30 days of such inquiry.',NULL,'4','MSB Registration & FINTRAC Notifications','Registration','MSB-06',false);

-- ---------------- Section 5: Client Identification & KYC ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','client_identification_kyc',27,'Trigger events','PCMLTFR',true,27,'Requirement',NULL,'Confirm the policy lists all identity-verification trigger events relevant to the business model.','Trigger events are specific, complete and testable.',NULL,'5','Client Identification & KYC','Triggers','KYC-01',false),
('policies_procedures','core_controls','client_identification_kyc',28,'Exemptions','PCMLTFR',true,28,'Requirement',NULL,'Confirm any statutory/sector exemptions are documented and differentiated from general trigger rules.','Exemptions are documented with conditions and do not contradict trigger requirements.',NULL,'5','Client Identification & KYC','Triggers','KYC-02',false),
('policies_procedures','core_controls','client_identification_kyc',29,'Government photo ID','PCMLTFR',true,29,'Requirement',NULL,'Confirm the government-issued photo ID method is described.','Policy states ID must be authentic, valid and current; method is usable in practice.',NULL,'5','Client Identification & KYC','Individuals','KYC-03',false),
('policies_procedures','core_controls','client_identification_kyc',30,'Non-face-to-face photo ID','PCMLTFR; FINTRAC Guidance',true,30,'Requirement',NULL,'Confirm non-face-to-face photo ID controls are described.','Policy requires technology/processes to assess authenticity and link the presenter to the ID.',NULL,'5','Client Identification & KYC','Individuals','KYC-04',false),
('policies_procedures','core_controls','client_identification_kyc',31,'Credit file method','PCMLTFR',true,31,'Requirement',NULL,'Confirm the credit file method criteria are described.','Policy states the file must satisfy the minimum age/currentness/tradeline and matching requirements, and be obtained at time of verification.',NULL,'5','Client Identification & KYC','Individuals','KYC-05',false),
('policies_procedures','core_controls','client_identification_kyc',32,'Dual-process method','PCMLTFR',true,32,'Requirement',NULL,'Confirm dual-process criteria are described.','Policy requires two different reliable sources and permitted information combinations.',NULL,'5','Client Identification & KYC','Individuals','KYC-06',false),
('policies_procedures','core_controls','client_identification_kyc',33,'Reliance / affiliate / member methods','PCMLTFR',true,33,'Requirement',NULL,'Confirm permitted reliance / affiliate / member methods are described if used.','Policy states when reliance is allowed, what prior method must have been used, and what matching/recordkeeping is required.',NULL,'5','Client Identification & KYC','Individuals','KYC-07',false),
('policies_procedures','core_controls','client_identification_kyc',34,'Children / persons lacking standard ID','PCMLTFR',true,34,'Requirement',NULL,'Confirm special-case procedures exist where relevant.','Policy provides a compliant path for minors or customers lacking standard verification documents where the business offers such products.',NULL,'5','Client Identification & KYC','Special situations','KYC-08',false),
('policies_procedures','core_controls','client_identification_kyc',35,'Entity verification','PCMLTFR',true,35,'Requirement',NULL,'Confirm entity verification procedures are described by entity type.','Acceptable records and required fields are defined for corporations/trusts/other entities as applicable.',NULL,'5','Client Identification & KYC','Entities','KYC-09',false),
('policies_procedures','core_controls','client_identification_kyc',36,'ID recordkeeping','PCMLTFR',true,36,'Requirement',NULL,'Confirm identity-verification recordkeeping requirements are described by method.','Policy states what must be kept for each method and for how long.',NULL,'5','Client Identification & KYC','Recordkeeping','KYC-10',false),
('policies_procedures','core_controls','client_identification_kyc',37,'Updating KYC','PCMLTFR',true,37,'Requirement',NULL,'Confirm there is a procedure for updating customer''s records.','Policy requires KYC information to be refreshed on a risk-based cadence or on material-change events.',NULL,'5','Client Identification & KYC','KYC Refresh','KYC-11',false);

-- ---------------- Section 6: Business Relationship & Ongoing Monitoring ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','business_relationships_monitoring',38,'When relationship is established','PCMLTFR',true,38,'Requirement',NULL,'Confirm the policy defines when a business relationship begins for the sector.','Start-of-relationship triggers are clear and aligned to sector rules.',NULL,'6','Business Relationship & Ongoing Monitoring','Lifecycle','BR-01',false),
('policies_procedures','core_controls','business_relationships_monitoring',39,'Purpose / intended nature','PCMLTFR',true,39,'Requirement',NULL,'Confirm the policy requires recording the purpose and intended nature of the business relationship.','Required record is clearly described and operationalized.',NULL,'6','Business Relationship & Ongoing Monitoring','Lifecycle','BR-02',false),
('policies_procedures','core_controls','business_relationships_monitoring',40,'When relationship ends','PCMLTFR',true,40,'Requirement',NULL,'Confirm the policy defines when a business relationship ends.','End-of-relationship logic is documented and usable by analysts.',NULL,'6','Business Relationship & Ongoing Monitoring','Lifecycle','BR-03',false),
('policies_procedures','core_controls','business_relationships_monitoring',41,'Ongoing monitoring framework','PCMLTFR',true,41,'Requirement',NULL,'Confirm the policy requires ongoing monitoring of business relationships.','Monitoring is risk-based and linked to the relationship record.',NULL,'6','Business Relationship & Ongoing Monitoring','Monitoring','BR-04',false),
('policies_procedures','core_controls','business_relationships_monitoring',42,'Enhanced due diligence','PCMLTFR',true,42,'Requirement',NULL,'Confirm higher-risk relationships receive enhanced measures.','Frequency/intensity of review increases with risk and is described in plain language.',NULL,'6','Business Relationship & Ongoing Monitoring','Monitoring','BR-05',false),
('policies_procedures','core_controls','business_relationships_monitoring',43,'Escalation of unusual activity','PCMLTFR',true,43,'Requirement',NULL,'Confirm unusual activity/investigation escalation is described.','The policy explains when monitoring output becomes investigation and/or STR consideration.',NULL,'6','Business Relationship & Ongoing Monitoring','Monitoring','BR-06',false),
('policies_procedures','core_controls','business_relationships_monitoring',44,'Derisking / demarketing','FINTRAC Guidance',true,44,'Best Practice',NULL,'Confirm the policy addresses derisking/demarketing procedures and (for larger institutions) ongoing monitoring of accounts already recommended for demarketing.','Policy defines criteria, governance, approvals, fair-treatment, recordkeeping; and ongoing monitoring of demarketing-flagged accounts where applicable.',NULL,'6','Business Relationship & Ongoing Monitoring','Monitoring','BR-07',true);

-- ---------------- Section 7: Third Party Determination ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','third_party_determination',45,'What a third party is','PCMLTFR',true,45,'Requirement',NULL,'Confirm the policy defines who a third party is.','The policy defines third party clearly.',NULL,'7','Third Party Determination','Definitions','TPD-01',false),
('policies_procedures','core_controls','third_party_determination',46,'Large cash transactions','PCMLTFR',true,46,'Requirement',NULL,'Confirm the policy requires third party determination when a large cash transaction trigger applies.','Large cash trigger is explicitly listed.',NULL,'7','Third Party Determination','Triggers','TPD-02',false),
('policies_procedures','core_controls','third_party_determination',47,'Large virtual currency transactions','PCMLTFR',true,47,'Requirement',NULL,'Confirm the policy requires third party determination when a large VC transaction trigger applies.','Large VC trigger is explicitly listed.',NULL,'7','Third Party Determination','Triggers','TPD-03',false),
('policies_procedures','core_controls','third_party_determination',48,'Information record / account opening scenarios','PCMLTFR',true,48,'Requirement',NULL,'Confirm the policy covers the applicable information-record / account-opening / signature-card third-party triggers for the sector.','Relevant sector triggers are explicitly listed.',NULL,'7','Third Party Determination','Triggers','TPD-04',false),
('policies_procedures','core_controls','third_party_determination',49,'How determination is made','PCMLTFR',true,49,'Requirement',NULL,'Confirm the policy explains how staff determine whether a third party exists.','Staff are instructed to ask the client, document the answer and escalate concerns.',NULL,'7','Third Party Determination','Process','TPD-05',false),
('policies_procedures','core_controls','third_party_determination',50,'Required fields','PCMLTFR',true,50,'Requirement',NULL,'Confirm the required third-party details are listed.','Required identifying details and relationship-to-client fields are spelled out.',NULL,'7','Third Party Determination','Recordkeeping','TPD-06',false),
('policies_procedures','core_controls','third_party_determination',51,'Unable to determine but suspected','PCMLTFR',true,51,'Requirement',NULL,'Confirm the policy addresses cases where a third party is suspected but cannot be confirmed.','Policy requires documenting suspicion and escalating appropriately.',NULL,'7','Third Party Determination','Escalation','TPD-07',false);

-- ---------------- Section 8: Beneficial Ownership & Discrepancy Reporting ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','beneficial_ownership_discrepancy',52,'25%+ ownership/control','PCMLTFR',true,52,'Requirement',NULL,'Confirm the policy requires identifying individuals who directly or indirectly own/control 25% or more, as applicable.','25% threshold and indirect ownership/control concepts are stated.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Baseline','BO-01',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',53,'BO Cannot be another corporation','PCMLTFR',true,53,'Requirement',NULL,'Confirm that the policy states that BO cannot be other corporations, trusts or other entities. They must be the individuals who are the owners or controllers of the entity.','BO must be a natural person, not another entity.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Baseline','BO-02',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',54,'Ownership / control / structure','PCMLTFR',true,54,'Requirement',NULL,'Confirm the policy requires obtaining information that establishes ownership, control and structure.','Analysts can see exactly what structure information should be collected.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Baseline','BO-03',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',55,'Corporation/trust/other-entity specifics','PCMLTFR',true,55,'Requirement',NULL,'Confirm the policy differentiates the data required for corporations, trusts and other entities.','Entity-type-specific fields are identified where applicable.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Baseline','BO-04',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',56,'Unable to confirm beneficial ownership','PCMLTFR',true,56,'Requirement',NULL,'Confirm the policy states what to do if beneficial ownership cannot be confirmed.','Reasonable measures, escalation, high-risk treatment and enhanced monitoring are required.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Escalation','BO-05',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',57,'No beneficial owner exists','PCMLTFR',true,57,'Requirement',NULL,'Confirm the policy states what to do where no beneficial owner exists.','Policy requires documenting rationale, structure reviewed and evidence supporting the conclusion.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Edge case','BO-06',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',58,'Material BO discrepancy definition','Corporations Canada (Oct 1, 2025)',true,58,'Requirement',NULL,'Confirm the policy defines a reportable / material beneficial ownership discrepancy where relevant.','Definition is clear enough for analysts to recognize the issue.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Discrepancy','BO-07',true),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',59,'Resolution process','Corporations Canada (Oct 1, 2025)',true,59,'Requirement',NULL,'Confirm the policy requires attempts to resolve a BO discrepancy before reporting it externally.','Resolution attempts, timing and ownership are documented.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Discrepancy','BO-08',true),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',60,'Reporting to Corporations Canada','Corporations Canada (Oct 1, 2025)',true,60,'Requirement',NULL,'Confirm the policy describes when and how to report an unresolved/material discrepancy to Corporations Canada.','Submission path, timing and evidence retention are described.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Discrepancy','BO-09',true),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',61,'FINTRAC escalation / suspicious activity link','PCMLTFR',true,61,'Requirement',NULL,'Confirm the policy routes suspicious BO discrepancies into suspicious transaction/escalation logic.','Suspicious BO issues are linked to STR/investigation escalation where appropriate.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Discrepancy','BO-10',false),
('policies_procedures','core_controls','beneficial_ownership_discrepancy',62,'BO records','PCMLTFR',true,62,'Requirement',NULL,'Confirm BO recordkeeping requirements are described.','BO records, measures taken and reporting acknowledgements are retained.',NULL,'8','Beneficial Ownership & Discrepancy Reporting','Recordkeeping','BO-11',false);

-- ---------------- Section 9: PEP / HIO ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','pep_hio_controls',63,'PEP/HIO categories','PCMLTFR',true,63,'Requirement',NULL,'Confirm the policy defines foreign PEPs, domestic PEPs, HIOs, family members and close associates.','All required categories are defined in usable language.',NULL,'9','PEP / HIO','Definitions','PEP-01',false),
('policies_procedures','core_controls','pep_hio_controls',64,'When screening occurs','PCMLTFR',true,64,'Requirement',NULL,'Confirm the policy states when PEP/HIO screening or determination occurs.','At minimum onboarding and relevant ongoing/trigger events are described.',NULL,'9','PEP / HIO','Screening','PEP-02',false),
('policies_procedures','core_controls','pep_hio_controls',65,'Foreign PEP lifecycle','PCMLTFR',true,65,'Requirement',NULL,'Confirm the policy states that foreign PEPs (and relevant foreign PEP family members) do not age out.','Foreign PEP status is treated as ongoing/indefinite.',NULL,'9','PEP / HIO','Lifecycle','PEP-03',false),
('policies_procedures','core_controls','pep_hio_controls',66,'Domestic PEP/HIO lifecycle','PCMLTFR',true,66,'Requirement',NULL,'Confirm the policy states when domestic PEP/HIO status ceases.','Five-year rule after leaving office or death is clearly stated.',NULL,'9','PEP / HIO','Lifecycle','PEP-04',false),
('policies_procedures','core_controls','pep_hio_controls',67,'Close associates','PCMLTFR',true,67,'Requirement',NULL,'Confirm the policy states when close associates cease to be treated as such.','Ceases when the relationship/connection no longer exists.',NULL,'9','PEP / HIO','Lifecycle','PEP-05',false),
('policies_procedures','core_controls','pep_hio_controls',68,'Source of funds / source of wealth','PCMLTFR',true,68,'Requirement',NULL,'Confirm the policy requires source of funds and/or source of wealth measures where required.','Required EDD elements are stated clearly.',NULL,'9','PEP / HIO','Enhanced measures','PEP-06',false),
('policies_procedures','core_controls','pep_hio_controls',69,'Senior management review / approval','PCMLTFR',true,69,'Requirement',NULL,'Confirm the policy requires senior management review/approval where required.','Approval/escalation requirement is clearly documented.',NULL,'9','PEP / HIO','Enhanced measures','PEP-07',false),
('policies_procedures','core_controls','pep_hio_controls',70,'High-risk treatment and monitoring','PCMLTFR',true,70,'Requirement',NULL,'Confirm the policy applies the required risk treatment and monitoring to PEP/HIO cases.','Risk treatment and enhanced ongoing monitoring are described.',NULL,'9','PEP / HIO','Enhanced measures','PEP-08',false),
('policies_procedures','core_controls','pep_hio_controls',71,'PEP/HIO records','PCMLTFR',true,71,'Requirement',NULL,'Confirm the policy lists the records to keep when a PEP/HIO is identified.','Determination, basis, source of funds/wealth and approvals are retained.',NULL,'9','PEP / HIO','Recordkeeping','PEP-09',false),
('policies_procedures','core_controls','pep_hio_controls',72,'How to determine','PCMLTFR',true,72,'Requirement',NULL,'Confirm the policy states how the entity will identify a PEP/HIO. E.g. asking, accessing a database, etc.','How to identify (asking, referring to credible source) is operationalized.',NULL,'9','PEP / HIO','Identifying','PEP-10',false);

-- ---------------- Section 10: Reporting Obligations ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','reporting_obligations',73,'Large cash reporting','PCMLTFR',true,73,'Requirement',NULL,'Confirm LCTR obligations, threshold, aggregation rule and timeline are described. Static with defined timeframe and time zone.','$10K threshold, 24-hour aggregation concept and 15-calendar-day reporting timeline are stated.',NULL,'10','Reporting Obligations','LCTR','REP-01',false),
('policies_procedures','core_controls','reporting_obligations',74,'Electronic funds transfer reporting','PCMLTFR',true,74,'Requirement',NULL,'Confirm EFTR obligations, threshold and timeline are described. Static with defined timeframe and time zone.','Threshold and 5-business-day reporting timeline are stated in operational terms.',NULL,'10','Reporting Obligations','EFTR','REP-02',false),
('policies_procedures','core_controls','reporting_obligations',75,'Large virtual currency transaction reporting','PCMLTFR',true,75,'Requirement',NULL,'Confirm LVCTR obligations, threshold, aggregation rule and timeline are described. Static with defined timeframe and time zone.','$10K threshold, 24-hour aggregation concept and 5-working-day reporting timeline are stated.',NULL,'10','Reporting Obligations','LVCTR','REP-03',false),
('policies_procedures','core_controls','reporting_obligations',76,'Suspicious transaction reporting','PCMLTFR',true,76,'Requirement',NULL,'Confirm suspicious transaction procedures cover attempted and completed transactions and the standard for filing.','Policy covers attempted and completed transactions and says reports must be filed as soon as practicable.',NULL,'10','Reporting Obligations','STR','REP-04',false),
('policies_procedures','core_controls','reporting_obligations',77,'EFT and VC travel rule','PCMLTFR',true,77,'Requirement',NULL,'Confirm travel rule requirements are addressed for EFT and VC transfer contexts.','Required data elements / exception-handling / escalation are covered for EFT and VC; policy does not misstate STR as a travel-rule report.',NULL,'10','Reporting Obligations','Travel rule','REP-05',false),
('policies_procedures','core_controls','reporting_obligations',78,'STR sanctions evasion coverage','PCMLTFR',true,78,'Requirement',NULL,'Confirm STR procedures expressly include sanctions evasion-related suspicions.','Attempted and completed sanctions evasion suspicions route to STR logic.',NULL,'10','Reporting Obligations','Sanctions evasion','REP-06',false),
('policies_procedures','core_controls','reporting_obligations',79,'Listed person or entity property report','PCMLTFR',true,79,'Requirement',NULL,'Confirm the current listed person or entity property report process is described.','Current report name/process and immediate timing are stated; superseded terminology is updated or cross-walked.',NULL,'10','Reporting Obligations','Property reporting','REP-07',false),
('policies_procedures','core_controls','reporting_obligations',80,'Parallel reporting / law enforcement link','PCMLTFA / PCMLTFR',true,80,'Requirement',NULL,'Confirm the policy explains when more than one report/escalation may be required (e.g., LPEPR plus STR, or law-enforcement notification under other laws).','Parallel reporting/escalation logic is documented.',NULL,'10','Reporting Obligations','Property reporting','REP-08',false),
('policies_procedures','core_controls','reporting_obligations',81,'Submission method','FINTRAC Guidance',true,81,'Requirement',NULL,'Confirm the policy tells staff how reports are filed (portal/API/manual fallback where relevant).','Submission channels and fallback/manual paths are specified.',NULL,'10','Reporting Obligations','Submission mechanics','REP-09',false),
('policies_procedures','core_controls','reporting_obligations',82,'Public-private partnership / project name field','FINTRAC Guidance',true,82,'Best Practice',NULL,'If applicable to the organization, confirm the policy explains when the STR public-private partnership/project-name field is used (e.g., CP North-style initiative).','Optional field usage is controlled and approved; N/A if not used.',NULL,'10','Reporting Obligations','Optional field','REP-10',false);

-- ---------------- Section 11: Sanctions & Ministerial Directives ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','sanctions_ministerial_directives',83,'Screening framework','UN Act / SEMA / JVCFOA',true,83,'Requirement',NULL,'Confirm sanctions screening procedures and watchlists are described.','Policy identifies the sanctions lists / screening controls used and escalation for hits.',NULL,'11','Sanctions & Ministerial Directives','Sanctions framework','SAN-01',false),
('policies_procedures','core_controls','sanctions_ministerial_directives',84,'Russia directive coverage','Ministerial Directive (Russia)',true,84,'Requirement',NULL,'Confirm current ministerial directive coverage for Russia is addressed where applicable to the firm.','Policy states operational measures for Russia-related directive requirements.',NULL,'11','Sanctions & Ministerial Directives','Ministerial directives','SAN-02',false),
('policies_procedures','core_controls','sanctions_ministerial_directives',85,'DPRK / North Korea directive coverage','Ministerial Directive (DPRK)',true,85,'Requirement',NULL,'Confirm current ministerial directive coverage for DPRK/North Korea is addressed where applicable to the firm.','Policy states operational measures for DPRK-related directive requirements.',NULL,'11','Sanctions & Ministerial Directives','Ministerial directives','SAN-03',false),
('policies_procedures','core_controls','sanctions_ministerial_directives',86,'Iran directive coverage','Ministerial Directive (Iran, Nov 2025)',true,86,'Requirement',NULL,'Confirm current ministerial directive coverage for Iran is addressed where applicable to the firm.','Policy states operational measures for Iran-related directive requirements.',NULL,'11','Sanctions & Ministerial Directives','Ministerial directives','SAN-04',true),
('policies_procedures','core_controls','sanctions_ministerial_directives',87,'Operational measures','Ministerial Directives',true,87,'Requirement',NULL,'Confirm the policy states the specific directive-related enhanced measures required (CDD, verification, recordkeeping, approvals, transaction restrictions/escalation).','Operational steps are clear enough for analysts to test.',NULL,'11','Sanctions & Ministerial Directives','Ministerial directives','SAN-05',false),
('policies_procedures','core_controls','sanctions_ministerial_directives',88,'Do-not-complete and escalation rules','Criminal Code / RIUNRST',true,88,'Requirement',NULL,'Confirm the policy addresses situations where transactions involving prohibited or listed property should not proceed and must be escalated.','Completion prohibition / escalation / notification logic is documented where relevant.',NULL,'11','Sanctions & Ministerial Directives','Terrorist property / listed property','SAN-06',false);

-- ---------------- Section 12: Recordkeeping ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','recordkeeping',89,'Retention period','PCMLTFR',true,89,'Requirement',NULL,'Confirm the policy states the applicable minimum retention period(s).','At least the minimum statutory retention period is stated, usually 5 years where applicable.',NULL,'12','Recordkeeping','Framework','RK-01',false),
('policies_procedures','core_controls','recordkeeping',90,'Sector-specific record list','PCMLTFR',true,90,'Requirement',NULL,'Confirm the policy lists the records relevant to the firm''s sector/products.','Record inventory is tailored to the actual business model.',NULL,'12','Recordkeeping','Framework','RK-02',false),
('policies_procedures','core_controls','recordkeeping',91,'Transaction records','PCMLTFR',true,91,'Requirement',NULL,'Confirm the policy describes key transaction records (LCT, EFT, LVCT, FX/VC exchange, etc.) relevant to the business.','Required record types and core fields are stated.',NULL,'12','Recordkeeping','Transactions','RK-03',false),
('policies_procedures','core_controls','recordkeeping',92,'Client and account records','PCMLTFR',true,92,'Requirement',NULL,'Confirm the policy describes required client / account / signature / intended use records where applicable.','Customer/account record requirements are operationalized.',NULL,'12','Recordkeeping','Clients','RK-04',false),
('policies_procedures','core_controls','recordkeeping',93,'Internal memorandum / rationale records','PCMLTFR',true,93,'Requirement',NULL,'Confirm the policy requires retaining investigation and reporting rationale records.','Internal STR decisioning / escalation notes are retained.',NULL,'12','Recordkeeping','Investigations','RK-05',false),
('policies_procedures','core_controls','recordkeeping',94,'Retrievability and audit trail','PCMLTFR',true,94,'Requirement',NULL,'Confirm the policy requires records to be retrievable and audit-ready.','Retrieval ownership, storage location and access controls are defined.',NULL,'12','Recordkeeping','Accessibility','RK-06',false),
('policies_procedures','core_controls','recordkeeping',95,'Agent / mandatary / service agreement records','PCMLTFR',true,95,'Requirement',NULL,'Confirm policies describe agreements and oversight records for agents/mandataries/service agreements where used.','Written agreements and monitoring/audit evidence are required.',NULL,'12','Recordkeeping','Agents','RK-07',false);

-- ---------------- Section 13: Training Program ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','training_program',96,'Training policy','PCMLTFR s.71',true,96,'Requirement',NULL,'Confirm a formal training policy or training section exists.','Training program is explicitly documented.',NULL,'13','Training Program','Framework','TRN-01',false),
('policies_procedures','core_controls','training_program',97,'Who must be trained','PCMLTFR s.71',true,97,'Requirement',NULL,'Confirm the policy defines who must be trained.','Employees, management and other relevant persons/agents are identified.',NULL,'13','Training Program','Audience','TRN-02',false),
('policies_procedures','core_controls','training_program',98,'Onboarding training','PCMLTFR s.71',true,98,'Requirement',NULL,'Confirm the policy requires AML training for new relevant staff at onboarding/initial hire or role change or those on long leave.','Onboarding timing is stated clearly.',NULL,'13','Training Program','Timing','TRN-03',false),
('policies_procedures','core_controls','training_program',99,'Ongoing training','PCMLTFR s.71',true,99,'Requirement',NULL,'Confirm the policy requires ongoing/refresher training.','Ongoing training cadence is stated (e.g., annual and event-driven updates).',NULL,'13','Training Program','Frequency','TRN-04',false),
('policies_procedures','core_controls','training_program',100,'Training content','PCMLTFR s.71',true,100,'Requirement',NULL,'Confirm the policy describes required AML/ATF training content.','Content covers obligations, red flags, sanctions/ministerial directives, KYC, BO, reporting, confidentiality and escalation.',NULL,'13','Training Program','Content','TRN-05',false),
('policies_procedures','core_controls','training_program',101,'Method of delivery','PCMLTFR s.71',true,101,'Requirement',NULL,'Confirm the policy states how training may be delivered.','Delivery channels/methods are defined (e.g., LMS, classroom, virtual, attestations).',NULL,'13','Training Program','Delivery','TRN-06',false),
('policies_procedures','core_controls','training_program',102,'Role-based training','PCMLTFR s.71',true,102,'Requirement',NULL,'Confirm enhanced role-based training is required where needed.','Higher-risk roles receive more targeted/deeper training.',NULL,'13','Training Program','Targeting','TRN-07',false),
('policies_procedures','core_controls','training_program',103,'Training records','PCMLTFR s.71',true,103,'Requirement',NULL,'Confirm the policy requires evidence of completion and exception tracking.','Attendance/completion logs and overdue tracking are required.',NULL,'13','Training Program','Evidence','TRN-08',false),
('policies_procedures','core_controls','training_program',104,'Regulatory change updates','PCMLTFR s.71',true,104,'Requirement',NULL,'Confirm training is updated for regulatory change.','Policy requires updates when laws, guidance or products/processes change.',NULL,'13','Training Program','Updates','TRN-09',false);

-- ---------------- Section 14: Law Enforcement, Disclosures & Self-Disclosure ----------------
INSERT INTO public.aml_program_question_templates
  (submodule, control_area, control_category, question_number, question_text, regulatory_reference, evidence_required, sort_order, regulatory_category, test_procedure, analyst_guidance, pass_criteria, max_points, section_code, section_name, subsection, question_code, is_new_or_updated)
VALUES
('policies_procedures','core_controls','law_enforcement_disclosure',105,'Production orders','PCMLTFA',true,105,'Requirement',NULL,'Confirm the policy identifies who handles production orders and related legal requests.','Ownership, legal/compliance escalation and logging are defined.',NULL,'14','Law Enforcement, Disclosures & Self-Disclosure','External requests','LED-01',false),
('policies_procedures','core_controls','law_enforcement_disclosure',106,'Law enforcement requests','PCMLTFA',true,106,'Requirement',NULL,'Confirm the policy identifies who handles law-enforcement information requests.','Requests are centralized, logged and approved before response.',NULL,'14','Law Enforcement, Disclosures & Self-Disclosure','External requests','LED-02',false),
('policies_procedures','core_controls','law_enforcement_disclosure',107,'FINTRAC disclosure requests','PCMLTFA',true,107,'Requirement',NULL,'Confirm the policy identifies who handles FINTRAC disclosure/information requests.','Ownership, timeliness and confidentiality controls are defined.',NULL,'14','Law Enforcement, Disclosures & Self-Disclosure','External requests','LED-03',false),
('policies_procedures','core_controls','law_enforcement_disclosure',108,'Anti-tipping-off / confidentiality','PCMLTFA',true,108,'Requirement',NULL,'Confirm the policy addresses confidentiality and tipping-off risks around investigations and external requests.','Confidentiality and need-to-know controls are described.',NULL,'14','Law Enforcement, Disclosures & Self-Disclosure','Confidentiality','LED-04',false),
('policies_procedures','core_controls','law_enforcement_disclosure',109,'Voluntary self-disclosure of non-compliance','FINTRAC Guidance',true,109,'Requirement',NULL,'Confirm the policy defines when material non-compliance should be escalated and considered for voluntary self-disclosure to FINTRAC.','Trigger, ownership, approval and documentation requirements are defined.',NULL,'14','Law Enforcement, Disclosures & Self-Disclosure','Self-disclosure','LED-05',false),
('policies_procedures','core_controls','law_enforcement_disclosure',110,'Remediation tracking','FINTRAC Guidance',true,110,'Requirement',NULL,'Confirm the self-disclosure / issue-management process requires root cause analysis, corrective action and validation of closure.','Issues are owned, remediated and re-tested to closure.',NULL,'14','Law Enforcement, Disclosures & Self-Disclosure','Self-disclosure','LED-06',false),
('policies_procedures','core_controls','law_enforcement_disclosure',111,'Periodic effectiveness testing','PCMLTFR s.71(1)(e)',true,111,'Requirement',NULL,'Confirm the policy requires the compliance regime to be independently/effectively reviewed at least every 2 years and tracked to closure.','Review cadence, scope and remediation tracking are defined.',NULL,'14','Law Enforcement, Disclosures & Self-Disclosure','Effectiveness review','LED-07',false);

NOTIFY pgrst, 'reload schema';
